### ISSUE TITLE
Callback record is orphaned if Customer provides alternative PhoneNumber during Callback

### ISSUE THREAD

**Issue by rickosaws** [aws-samples/amazon-connect-rules-engine#29]
When a customer accepts a Callback and provides an alternative Phone Number (to that recorded in OriginalCustomerNumber) the ConnectDeleteCallback function is unable to remove the record from the callback-ddb table.

This results in callback records remaining in the callback-ddb table until the record TTL expires

**Comment by jospas** [comment]
Resolved in pull request thanks Rick!
