### ISSUE TITLE
Serverless Framework issue with AWS_PROFILE

### ISSUE THREAD

**Issue by aamoroso** [aws-samples/amazon-connect-rules-engine#41]
This is a general Serverless Framework issue but you may want to incorporate a fix or at lease a mention in the README.

If you export an AWS_PROFILE and run the script `scripts/rules_engine_serverless_deploy.sh` sls will fail unless you set

`export AWS_SDK_LOAD_CONFIG="true"`

**Comment by jospas** [comment]
Thanks Adrian, I can add this in the sample and update the docs, is this a recent requirement for serverless?

I have been replying on just setting AWS_PROFILE to the named profile.

Josh

**Comment by aamoroso** [comment]
Hey Josh, I've had to do this for a couple years now -  if I use the environment for profile specification... unless there's something weird with my own environment :)
